app/models.py
from . import db
from datetime import datetime
from flask_login import UserMixin

from werkzeug.security import check_password_hash, generate_password_hash
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(20), index=True)
    email = db.Column(db.String(64), index=True, unique=True)
    password_hashed = db.Column(db.String(128))
    todos = db.relationship('Todo', backref='user', lazy='dynamic')
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    @property
    def password(self):
        raise AttributeError('A senha não é um atributo com permissão de leitura')
    
    @password.setter
    def password(self, password):
        self.password_hashed = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hashed, password)
        
class Todo(db.Model):
    __tablename__ = 'todos'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(20), index=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

app/__init__.py
from flask import Flask
from flask_login import LoginManager, AnonymousUserMixin
from flask_bootstrap import Bootstrap
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from config import config


login_manager = LoginManager()
bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    # migrate.init_app(app, db)

    # calling controllers
    from .controllers.home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    from .controllers.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

app/controllers/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/controllers/home/views.py
from . import home
from flask import render_template, flash, redirect, url_for, session
from flask_login import current_user
from ...form import TodoForm
from ...models import Todo
from ... import db

@home.route('/', methods=['GET', 'POST'])
def index():
    form = TodoForm()
    todos = None

    if current_user.is_authenticated:
        todos = Todo.query.filter_by(user_id=current_user.id).all()

    if form.validate_on_submit():
        todo = Todo.query.filter_by(title=form.title.data).first()
        session.pop('message', None)

        if todo is None:            
            t = Todo()
            t.title = form.title.data
            t.user_id = current_user.id
            
            db.session.add(t)
            db.session.commit()
            flash('Task added successfully!')
            flash('success')
            return redirect(url_for('.index'))
        else:
            flash('Task already exist!')
            flash('error')
            return redirect(url_for('.index'))
        
    return render_template('home/index.html', form=form, todos=todos)

@home.route('/task/delete/<int:id>')
def delete_task(id):
    todo = Todo.query.filter_by(id=id).first()
    
    if todo is not None:
        db.session.delete(todo)
        db.session.commit()
        flash('Task removed successfully!')
        flash('success')
    
    flash('Task is not removed')
    flash('error')

    return redirect(url_for('.index'))

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap4-bubblegum.min.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
{% endblock %}

{% block navbar %}
<div class="jumbotron bg-danger text-white radius-0 mb-0">
    <div class="container">
        <h1 class="display-1 text-chicle text-light">Outrora List</h1>
        <span class="lead text-light">Gerenciador de tarefas.</span>
    </div>
</div>
{% endblock %}

<div>
    <div class="container py-5">
        {% block content %}{% endblock %}
    </div>
</div>

{% block footer %}
    <footer class="footer text-center">
        <h4 class=" jump-30">Outrora - todos os direitos reservados</h4>
        <p>
            <a href="#">Login</a>
        </p>
    </footer>
{% endblock %}

app/templates/home/index.html
{% extends 'base.html' %}


{% block content %}
    <div class="container py-5">
        {% if current_user.is_authenticated %}
            <p class="text-center"> 
                Seja bem-vindo {{ current_user.name }}
                <a href="{{ url_for('auth.logout') }}">Logout</a>
            </p>
            <div class="content-outrora">
                <form action="{{ url_for('home.index') }}" method="POST">
                    {{ form.csrf_token }}
                    <div class="input-group mb-3">
                        {{ form.title(class='form-control form-control-lg', placeholder='Título da tarefa') }}
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-lg btn-outline-danger" onclick="addTodo()" type="button">Adicionar</button>
                        </div>
                    </div>
                </form>
        
                <!-- Break Line in 100px -->
                <div class="jump-100"></div>
        
                <div class="col-md-12">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Título</th>
                                <th>Ação</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for todo in todos %}
                                <tr>    
                                    <td>{{todo.title}}</td>
                                    <td>         
                                        <a href="{{ url_for('home.delete_task', id=todo.id  ) }}" class="btn btn-danger">
                                            <i class="fas fa-trash-alt icon-white"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% else %}
            <div class="jumbotron text-center">
                <h1 class="display-3">Olá visitante</h1>
                <p class="lead mt-5"> Você precisa está logado para acessar o sistema.</p>
                <hr class="my-4">
                <p>Clique no botão abaixo para logar no sistema.
                </p>
            
                <p class="lead">
                    <a class="btn btn-primary btn-lg" href="{{ url_for('auth.login') }}" role="button">Logar</a>
                </p>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="http://codeseven.github.io/toastr/build/toastr.min.js"></script>
    <script>
        var message = "{{ get_flashed_messages()[0] }}"
        var color = "{{ get_flashed_messages()[1] }}"

        localStorage.setItem('message', message);
        localStorage.setItem('color', color);
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": true,
            "positionClass": "toast-bottom-right",
            "preventDuplicates": true,
            "onclick": null,
            "showDuration": "500",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    
        $(document).ready(function () {
            if(localStorage.getItem("message")){
                toastr["" + localStorage.getItem('color')](localStorage.getItem('message'))
            }
        })

    </script>
{% endblock %}